"""Keep changing version metadata out of project-wide compiler flags."""

import datetime
import json
import os
from pathlib import Path
import subprocess


def git_version(project_dir):
    override = os.environ.get("AIRBRIDGE_VERSION")
    if override:
        return override
    try:
        return subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=project_dir, stderr=subprocess.DEVNULL, text=True,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def build_date():
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if epoch:
        return datetime.datetime.fromtimestamp(
            int(epoch), datetime.timezone.utc,
        ).strftime("%Y-%m-%dT%H:%M")
    return datetime.datetime.now().strftime("%Y-%m-%dT%H:%M")


def generate_header(project_dir, output_dir):
    content = (
        "// Auto-generated by generate_build_info.py, do not edit.\n"
        "#pragma once\n\n"
        f"#define AIRBRIDGE_VERSION {json.dumps(git_version(project_dir))}\n"
        f"#define AIRBRIDGE_BUILD_DATE {json.dumps(build_date())}\n"
    )
    header = Path(output_dir) / "build_info_generated.h"
    if not header.exists() or header.read_text(encoding="utf-8") != content:
        header.parent.mkdir(parents=True, exist_ok=True)
        header.write_text(content, encoding="utf-8")


try:
    Import("env")
except NameError:
    env = None

if env is not None:
    # Each environment owns its metadata; only build_info.cpp includes it.
    output_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")
    generate_header(env.subst("$PROJECT_DIR"), output_dir)
    env.Append(CPPPATH=[output_dir])
